# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
schedules:
- cron: 0 6 * * 0,1,4
  branches:
    include:
    - refs/heads/main
  always: true
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Phase_1
  displayName: Agent job 1
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: ConsoleAppUnitTester.exe
...
